import type { Metadata } from "next";
import Image from "next/image";
import { Inter } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "./ConvexClientProvider";
import { Header } from "./header";
import { Toaster } from "@/components/ui/sonner";
import { Footer } from "./footer";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GCTU FileDrive",
  description: "Generated by NextJs",
  icons: {
    icon: "/title_logo.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Background Hero Logo */}
          <div className="fixed inset-0 z-[-1] pointer-events-none flex items-center justify-center opacity-5 dark:opacity-10">
            <Image
              src="/logo.png"
              alt="Background Logo"
              width={800}
              height={800}
              className="w-[90vw] max-w-[800px] h-auto object-contain"
              priority
            />
          </div>

          <ConvexClientProvider>
            <Toaster richColors />
            <Header />
            {children}
            <Footer />
          </ConvexClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
